package com.artificialss.showcase.ui.localization

data class AppStrings(
    // Login
    val loginTitle: String,
    val loginSubtitle: String,
    val loginEmail: String,
    val loginPassword: String,
    val loginShowPassword: String,
    val loginHidePassword: String,
    val loginRememberMe: String,
    val loginForgotPassword: String,
    val loginSignIn: String,
    val loginSigningIn: String,
    val loginOr: String,
    val loginNoAccount: String,
    val loginSignUp: String,
    val loginFooter: String,
    // Navigation
    val navHome: String,
    val navMap: String,
    val navGallery: String,
    val navProfile: String,
    val navUiKit: String,
    // Map
    val mapAddress: String,
    val mapHours: String,
    val mapNavigate: String,
    val mapAiPowered: String,
    // Restaurant cuisine types
    val cuisineItalian: String,
    val cuisineJapanese: String,
    val cuisineSpanishGrill: String,
    val cuisineFrenchCafe: String,
    val cuisineThai: String,
    val cuisineAmerican: String,
    val cuisineSpanishSeafood: String,
    val cuisineItalianPasta: String,
    val cuisineHealthyBowls: String,
    val cuisineDesserts: String,
    // Dashboard
    val dashWelcome: String,
    val dashAnalytics: String,
    val dashBitcoin: String,
    val dashWeeklyActivity: String,
    val dashCategoryBreakdown: String,
    val dashSpendingByCategory: String,
    val dashTotal: String,
    val dashRecentTransactions: String,
    val dashSeeAll: String,
    val dashAllTransactions: String,
    val dashSend: String,
    val dashReceive: String,
    val dashPay: String,
    val dashHistory: String,
    val dashNoData: String,
    // Chart periods
    val chartPeriodWeek: String,
    val chartPeriodMonth: String,
    val chartPeriodQuarter: String,
    // Transaction categories
    val catFood: String,
    val catTransport: String,
    val catEntertainment: String,
    val catShopping: String,
    val catBills: String,
    val catHealth: String,
    val catTravel: String,
    val catOther: String,
    // Bar chart time labels
    val chartMon: String,
    val chartTue: String,
    val chartWed: String,
    val chartThu: String,
    val chartFri: String,
    val chartSat: String,
    val chartSun: String,
    val chartWeek1: String,
    val chartWeek2: String,
    val chartWeek3: String,
    val chartWeek4: String,
    val chartJan: String,
    val chartFeb: String,
    val chartMar: String,
    // Gallery
    val galleryTitle: String,
    // Welcome dialog
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val welcomeWhoWeAre: String,
    val welcomeWhoWeAreText: String,
    val welcomeHighlights: String,
    val welcomeHighlight1: String,
    val welcomeHighlight2: String,
    val welcomeHighlight3: String,
    val welcomeHighlight4: String,
    val welcomeHighlight5: String,
    val welcomeThemeHint: String,
    val welcomeBuiltWith: String,
    val welcomeExplore: String,
)

fun englishStrings() = AppStrings(
    loginTitle = "Welcome Back",
    loginSubtitle = "Sign in to your account",
    loginEmail = "Email",
    loginPassword = "Password",
    loginShowPassword = "Show password",
    loginHidePassword = "Hide password",
    loginRememberMe = "Remember me",
    loginForgotPassword = "Forgot password?",
    loginSignIn = "Sign In",
    loginSigningIn = "Signing In...",
    loginOr = "OR",
    loginNoAccount = "Don't have an account?",
    loginSignUp = "Sign Up",
    loginFooter = "By signing in, you agree to our Terms of Service and Privacy Policy",
    navHome = "Home",
    navMap = "Map",
    navGallery = "Gallery",
    navProfile = "Profile",
    navUiKit = "UI Kit",
    mapAddress = "Address",
    mapHours = "Hours",
    mapNavigate = "Navigate",
    mapAiPowered = "AI Powered",
    cuisineItalian = "Italian",
    cuisineJapanese = "Japanese",
    cuisineSpanishGrill = "Spanish Grill",
    cuisineFrenchCafe = "French Café",
    cuisineThai = "Thai",
    cuisineAmerican = "American",
    cuisineSpanishSeafood = "Spanish Seafood",
    cuisineItalianPasta = "Italian Pasta",
    cuisineHealthyBowls = "Healthy Bowls",
    cuisineDesserts = "Desserts",
    dashWelcome = "Welcome",
    dashAnalytics = "Analytics",
    dashBitcoin = "Bitcoin Price",
    dashWeeklyActivity = "Weekly Activity",
    dashCategoryBreakdown = "Category Breakdown",
    dashSpendingByCategory = "Spending by Category",
    dashTotal = "Total",
    dashRecentTransactions = "Recent Transactions",
    dashSeeAll = "See all",
    dashAllTransactions = "All Transactions",
    dashSend = "Send",
    dashReceive = "Receive",
    dashPay = "Pay",
    dashHistory = "History",
    dashNoData = "No data available",
    chartPeriodWeek = "This Week",
    chartPeriodMonth = "This Month",
    chartPeriodQuarter = "This Quarter",
    catFood = "Food & Dining",
    catTransport = "Transport",
    catEntertainment = "Entertainment",
    catShopping = "Shopping",
    catBills = "Bills & Utilities",
    catHealth = "Health",
    catTravel = "Travel",
    catOther = "Other",
    chartMon = "Mon",
    chartTue = "Tue",
    chartWed = "Wed",
    chartThu = "Thu",
    chartFri = "Fri",
    chartSat = "Sat",
    chartSun = "Sun",
    chartWeek1 = "Week 1",
    chartWeek2 = "Week 2",
    chartWeek3 = "Week 3",
    chartWeek4 = "Week 4",
    chartJan = "Jan",
    chartFeb = "Feb",
    chartMar = "Mar",
    galleryTitle = "Gallery",
    welcomeTitle = "Artificialss Showcase",
    welcomeSubtitle = "Technical Demo Application",
    welcomeWhoWeAre = "Who we are",
    welcomeWhoWeAreText = "Artificialss builds cross-platform mobile apps with modern architectures and pixel-perfect UI.",
    welcomeHighlights = "Highlights",
    welcomeHighlight1 = "Canvas charts with touch tooltips",
    welcomeHighlight2 = "Interactive platform map",
    welcomeHighlight3 = "Image gallery with async loading",
    welcomeHighlight4 = "MVP + Room + Koin + Apollo",
    welcomeHighlight5 = "Live theme, font, and color switching",
    welcomeThemeHint = "Use the bottom bar to switch themes, fonts, and colors in real time.",
    welcomeBuiltWith = "Built with Kotlin Multiplatform + Compose",
    welcomeExplore = "Explore the App",
)

fun spanishStrings() = AppStrings(
    loginTitle = "Bienvenido",
    loginSubtitle = "Inicia sesión en tu cuenta",
    loginEmail = "Correo electrónico",
    loginPassword = "Contraseña",
    loginShowPassword = "Mostrar contraseña",
    loginHidePassword = "Ocultar contraseña",
    loginRememberMe = "Recuérdame",
    loginForgotPassword = "¿Olvidaste tu contraseña?",
    loginSignIn = "Iniciar sesión",
    loginSigningIn = "Iniciando sesión...",
    loginOr = "O",
    loginNoAccount = "¿No tienes cuenta?",
    loginSignUp = "Registrarse",
    loginFooter = "Al iniciar sesión, aceptas nuestros Términos de servicio y Política de privacidad",
    navHome = "Inicio",
    navMap = "Mapa",
    navGallery = "Galería",
    navProfile = "Perfil",
    navUiKit = "UI Kit",
    mapAddress = "Dirección",
    mapHours = "Horario",
    mapNavigate = "Navegar",
    mapAiPowered = "Potenciado por IA",
    cuisineItalian = "Italiana",
    cuisineJapanese = "Japonesa",
    cuisineSpanishGrill = "Parrilla Española",
    cuisineFrenchCafe = "Café Francés",
    cuisineThai = "Tailandesa",
    cuisineAmerican = "Americana",
    cuisineSpanishSeafood = "Mariscos Españoles",
    cuisineItalianPasta = "Pasta Italiana",
    cuisineHealthyBowls = "Bowls Saludables",
    cuisineDesserts = "Postres",
    dashWelcome = "Bienvenido",
    dashAnalytics = "Analíticas",
    dashBitcoin = "Precio Bitcoin",
    dashWeeklyActivity = "Actividad Semanal",
    dashCategoryBreakdown = "Desglose por Categoría",
    dashSpendingByCategory = "Gasto por Categoría",
    dashTotal = "Total",
    dashRecentTransactions = "Transacciones Recientes",
    dashSeeAll = "Ver todo",
    dashAllTransactions = "Todas las Transacciones",
    dashSend = "Enviar",
    dashReceive = "Recibir",
    dashPay = "Pagar",
    dashHistory = "Historial",
    dashNoData = "Sin datos disponibles",
    chartPeriodWeek = "Esta semana",
    chartPeriodMonth = "Este mes",
    chartPeriodQuarter = "Este trimestre",
    catFood = "Comida",
    catTransport = "Transporte",
    catEntertainment = "Entretenimiento",
    catShopping = "Compras",
    catBills = "Facturas",
    catHealth = "Salud",
    catTravel = "Viajes",
    catOther = "Otros",
    chartMon = "Lun",
    chartTue = "Mar",
    chartWed = "Mié",
    chartThu = "Jue",
    chartFri = "Vie",
    chartSat = "Sáb",
    chartSun = "Dom",
    chartWeek1 = "Semana 1",
    chartWeek2 = "Semana 2",
    chartWeek3 = "Semana 3",
    chartWeek4 = "Semana 4",
    chartJan = "Ene",
    chartFeb = "Feb",
    chartMar = "Mar",
    galleryTitle = "Galería",
    welcomeTitle = "Showcase de Artificialss",
    welcomeSubtitle = "Aplicación de Demostración Técnica",
    welcomeWhoWeAre = "Quiénes somos",
    welcomeWhoWeAreText = "Artificialss desarrolla apps móviles multiplataforma con arquitecturas modernas e interfaces pixel-perfect.",
    welcomeHighlights = "Destacados",
    welcomeHighlight1 = "Gráficos Canvas con tooltips táctiles",
    welcomeHighlight2 = "Mapa interactivo multiplataforma",
    welcomeHighlight3 = "Galería de imágenes con carga asíncrona",
    welcomeHighlight4 = "MVP + Room + Koin + Apollo",
    welcomeHighlight5 = "Cambio de tema, fuente y color en vivo",
    welcomeThemeHint = "Usa la barra inferior para cambiar temas, fuentes y colores en tiempo real.",
    welcomeBuiltWith = "Construido con Kotlin Multiplatform + Compose",
    welcomeExplore = "Explorar la App",
)
